name: Puppeteer and Lighthouse Run

on:
  workflow_run:
    workflows: ["Deploy Next.js site to Pages"]
    types:
      - completed

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run main.mjs
      run: node scripts/main.mjs

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output-artifacts
        path: auto_*